site_name: !!python/object/apply:os.getenv [DOCS_NAME, "Link Embeds Plugin"]
repo_url: https://github.com/Aetherinox/mkdocs-link-embeds
repo_name: Aetherinox/mkdocs-link-embeds
edit_uri: edit/main/docs/docs/
site_author: Aetherinox

markdown_extensions:
  - toc:
      permalink: true
  - abbr
  - admonition
  - attr_list
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: Aetherinox
      repo: mkdocs-link-embeds
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - material/overrides/.icons
  - md_in_html
  - def_list
  - footnotes
  - tables
  - pymdownx.inlinehilite
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tabbed
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.blocks.html
  - pymdownx.details
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: Aetherinox
      repo: obsidian-gistr
  - pymdownx.keys
  - pymdownx.snippets:
      url_download: true
      auto_append:
        - includes/abbreviations.md

theme:
  highlightjs: true
  hljs_languages:
    - yaml
    - yml
    - rust
    - markdown
  icon:
    note: fontawesome/solid/note-sticky
    abstract: fontawesome/solid/book
    info: fontawesome/solid/circle-info
    tip: fontawesome/solid/bullhorn
    success: fontawesome/solid/check
    question: fontawesome/solid/circle-question
    warning: fontawesome/solid/triangle-exclamation
    failure: fontawesome/solid/bomb
    danger: fontawesome/solid/skull
    bug: fontawesome/solid/robot
    example: fontawesome/solid/flask
    quote: fontawesome/solid/quote-left
    annotation: material/arrow-right-circle
    tag:
      html: fontawesome/brands/html5
      js: fontawesome/brands/js
      css:  fontawesome/brands/css3
    repo: fontawesome/brands/git-alt 
  name: material
  custom_dir: material/overrides
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      accent: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: gistr
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo
  features:
    - announce.dismiss
    - toc.follow
    - content.action.edit
    - content.action.view
    - content.tooltips
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate 
    - content.code.select
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.tracking
    - navigation.path
    - navigation.top

# Hooks
hooks:
  - material/overrides/hooks/shortcodes.py
  - material/overrides/hooks/translations.py

extra_css:
  - stylesheets/extra.css?v1.001

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

nav:
  - Home: 'home.md'
  - Demo: 'demo.md'
  - Setup:
    - Install: 'setup/install.md'
    - Stylesheet: 'setup/stylesheet.md'
  - Usage:
    - Properties: 'usage/properties.md'
    - Configs: 'usage/configs.md'
    - Formatting: 'usage/formatting.md'
  - About:
    - Changelog: 'about/changelog.md'
    - License: 'about/license.md'
    - Conventions: 'about/conventions.md'


plugins:
  - tags
  - link-embeds:
      enabled: true
      name_default: "Untitled Link"
      desc_default: "No description found"
      image_default: "https://github.com/Aetherinox/mkdocs-link-embeds/assets/118329232/c0298d98-0910-4235-a88f-0c3e2f704ba7"
      image_disabled: false
      favicon_default: "https://github.com/Aetherinox/mkdocs-link-embeds/assets/118329232/13a151b1-d7f9-4e27-909b-a26986ab0954"
      favicon_disabled: false
      favicon_size: 25
      target: "blank"
      accent: "FFFFFF1A"
      verbose: false
  - git-committers:
      repository: Aetherinox/mkdocs-link-embeds
      docs_path: docs/docs/
      branch: main
      token: !!python/object/apply:os.getenv [GH_TOKEN, "NULL"]
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - git-revision-date-localized:
      type: timeago
      enabled: true
  - git-authors:
      show_contribution: true
      sort_authors_by: name
      exclude:
          - index.md
      enabled: true
  - redirects:
      redirect_maps:
        docs/home.md: home.md

extra:
  generator: false
  consent:
    title: Cookie Consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

copyright: >
  Copyright &copy; 2024 - Aetherinox